ts_server:
  crawl:
    enable: true
    time_interval: 10000
    buffer_size: 1000
  data_base:
    drvier_name: mysql
    url: cdb-rxranzeo.cd.tencentcdb.com:10084
    user: root
    pwd: Ca66771111
    db: ts
    set_max_open_conns: 10
    set_max_idle_conns: 5
  mq:
    enable: false
    url: amqp://root:root@aliyun.yanyan.site:5672
    queue: trace-data=queue
app_server:
  host:
    - ip: 127.0.0.1
      port: 8080
